### ISSUE TITLE
Add event name truncation

### ISSUE THREAD

**Issue by ellenli** [upnextinc/upnext#15]
![image](https://user-images.githubusercontent.com/933419/37732289-ff3d9da8-2d1a-11e8-8712-28a44fbfe986.png)

**Comment by mattq** [comment]
This would be great! I have a related issue when I use my laptop when the event is too long to display:

<img width="486" alt="safari_2018-03-23 10-41-46 2x" src="https://user-images.githubusercontent.com/573182/37835561-d4574d7e-2e86-11e8-9e99-4ecdbcf337d5.png">

**Comment by ellenli** [comment]
Oh dang, I've never seen that before @mattq. What's your OS version and what other apps do you have in your menu bar?

**Comment by mattq** [comment]
OS 10.13.1 and… a lot of apps. 

<img width="639" alt="teampaper snap_2018-03-23 10-47-59 2x" src="https://user-images.githubusercontent.com/573182/37835914-ab4869da-2e87-11e8-8be4-9a5387f0ff5e.png">

From left to right: HighSierraMediaKey, Dropbox, Adobe CC, WallCat, Citrix, Fantastical, Cloud, Shush, Alfred, Duo, 1Password, Sizeup, Amphetamine, Craft Manager, Bluetooth, TabNotes, battery, wifi, volume, Teampaper Snap, Itsycal, and the time. 

I use Vanilla to hide them most of the time, and your app worked well on my external monitor. But now that I'm using my laptop, there wasn't enough room, even with Vanilla enabled.

**Comment by ellenli** [comment]
Hm. I wonder if it's macOS or Vanilla doing the wrapping, because when mine overflows, it just disappears entirely (instead of wrapping). Have you seen any other menu bar strings wrap before @mattq?

**Comment by mattq** [comment]
I tried it with both with and without Vanilla after a restart, had no effect and still was wrapping. I'm trying out Bartender to see if this will help fix my icon issues :) 

Thanks for the tip on CopyClip!

**Comment by eapache** [comment]
On my mac it doesn't wrap when it gets too long, it just... disappears? It was confusing for a while because I thought it kept crashing but it turns out it was just unable to display anything.
