### ISSUE TITLE
Support multiple calendars

### ISSUE THREAD

**Issue by ellenli** [upnextinc/upnext#3]

**Comment by dcousineau** [comment]
Not sure if this is what you intended by this issue, but making sure to open the meeting invite with the right google account would be great.

I noticed Fantastical wraps links using this structure: `https://accounts.google.com/AccountChooser?Email=myname@company.tld&continue=https://meet.google.com/the-meet-id` which seems to switch to the correct google account for me!

**Comment by ellenli** [comment]
That's so useful to know. Thanks @dcousineau!

**Comment by rwoodmass** [comment]
Second this feature request! I have two jobs, and it would be really helpful if the tool could show my next event regardless of which calendar it's in.

**Comment by caffo** [comment]
Just being able to pick multiple calendars from the dropdown would be perfect.

**Comment by jtoy** [comment]
I would love this as well!

**Comment by ianhinder** [comment]
I have several work and personal calendars that I would like to monitor with Up Next. At the moment, I need to select just the main one, which will miss certain events.  It would be really great if I could select multiple calendars, and Up Next would show the next event from any of them.

Note that despite the title of this issue, I am not using Google calendars, but both Exchange and WebDAV.  All my calendars show up in the menu already, so just being able to select multiple would solve my problem.

**Comment by jeffmohr** [comment]
+1 would be great to include multiple calendars at the same time.

**Comment by rileybrook** [comment]
Would also love this!

**Comment by MGCanada** [comment]
Same! would love to monitor my sports teams calendars for upcoming games and each one is on it's own calendar.
