### ISSUE TITLE
Countdown gets out of sync

### ISSUE THREAD

**Issue by KevinGutowski** [upnextinc/upnext#49]
I unfortunately had to turn off the countdown timer as it seems to get stuck for me often. Toggling the option on and off in preferences seems to get it working for a little while but then I will look at it later and it will stay stuck again. Let me know what other info would be most helpful in debugging this!

**Comment by JensHendar** [comment]
I have the same issue, but for me the toggling just updates it once and then it stops again.

**Comment by fv0** [comment]
Yes same here. This is the most important feature for me personally. Great little tool by the way. Use it daily.
