### ISSUE TITLE
CPU zapping

### ISSUE THREAD

**Issue by droptopshopbob** [upnextinc/upnext#55]
i've used up-next for a long time. staple part of my daily workflow and super useful except that I think after the latest update, it's causing calendaragent and calendarwidget processes to dominate cpu load. My cat loves it my macbook fan is running like crazy, but I hate it because it degrades everything else I'm working on to the point that it becomes unworkable. I ran through every other possibility to narrow it down to up-next. Adding a video showing activity monitor with no other calendar syncing apps running > launching up-next > and the quitting up-next. Not sure if anything can be done, but hoping you'll look into it!

<img width="542" alt="Screen Shot 2021-01-16 at 4 01 22 PM" src="https://user-images.githubusercontent.com/77553656/104824026-2b102280-5814-11eb-876a-e77b9ccc2b0b.png">

https://user-images.githubusercontent.com/77553656/104823987-e8e6e100-5813-11eb-851f-cfedf5a53589.mp4

**Comment by jtgrenz** [comment]
I've also started noticing this. I thought maybe my calendar settings were corrupted, so I blew away my calendar plist files and resynced but that didn't help. As soon as I close up-next, CalenderAgent CPU drops away but as soon as I launch it to spikes to a minimum of 30% and climbs as high as 120%. I woke up to my MacBook fans going crazy but nothing was open and I had been asleep.

**Comment by mbxtr** [comment]
Chiming in, I've got the same problem as well. I was recently wondering why my fans were spinning with no CPU-intensive apps running. I looked in Activity Monitor and saw CalendarAgent spiking high in CPU percentage. I'm also on Catalina.

<img width="255" alt="Screen Shot 2021-02-03 at 10 40 47 AM" src="https://user-images.githubusercontent.com/238096/106779375-8a3fa680-660c-11eb-9027-7e611651bec9.png">

**Comment by gabriellanata** [comment]
Same for me, the CPU issues are fixed as soon as I close the app. It even stays with the fans at max speed when the laptop is closed.

**Comment by droptopshopbob** [comment]
checking in on this. it wasn't an issue before one of the big updates last year. 
would like to start using the app again!

**Comment by alecjacobs5401** [comment]
Bumping this as well. While using `Up Next`, my `CalendarAgent` is frequently >100% CPU usage.

**Comment by dnunes-domaintools** [comment]
Add +1 to me on this as well. CalendarAgent+CalendarWidgetExtension uses ~50% CPU:
![image](https://user-images.githubusercontent.com/82976465/130081341-0c6db7aa-b01d-489d-8b53-51634860448f.png)

Stopping Up Next causes the CPU to go back to normal. Restarting it and those processes are back up there. I'm on Up Next v1.0.1 and OS X 11.3. For reference I have ~10 meetings/day in case this is something at all related to meeting volume

**Comment by pllgr** [comment]
Same happens to me. When Up Next is running my CalendarAgent takes up most of my CPU and my fan goes crazy.

**Comment by fjaguero** [comment]
This happens to me as well with macOS Monterey and an M1.
<img width="505" alt="image" src="https://user-images.githubusercontent.com/716123/141976858-8cf02418-3ff7-4e08-8712-1af85e36e16c.png">

<img width="393" alt="image" src="https://user-images.githubusercontent.com/716123/141976803-1b0a283a-c3ff-4496-815e-1b7731458713.png">

**Comment by ikuspegi** [comment]
Has there been any progress on this?
Same with a 2021 Macbook pro M1 pro, 16GB RAM. Consistently using 30-50% CPU. I've seen it go as high as 80%.
Maybe an errant loop somewhere?
Bellow, a sample of the process  CalendarAgent (if that helps anything), acquired in Activity monitor > ... > Sample process (CalendarAgent)
[Sample of CalendarAgent.txt](https://github.com/ellenli/up-next/files/7899686/Sample.of.CalendarAgent.txt)
